# Generated by Django 5.1 on 2024-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_prompt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
