# Generated by Django 5.1 on 2024-08-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_customuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assistant_response',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_prompt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
